server:
  port: 10010
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://192.168.53.244:3306/epp_manager?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Amssy@123
    dbcp2:
      validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  redis:
#    host: 192.168.20.172
    port: 6379
    password: foobared
    jedis:
      pool:
        max-active: 1024
        max-wait: 10s
        max-idle: 800
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tk.lemi.outsource.authorizationcenter.dao

eureka:
  client:
    service-url:
      default: http://127.0.0.1:8761/eureka/